"use client";
import React, { useState } from "react";
import Link from "next/link";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { getData, postData, patchData } from "@/core/api/apiHandler";
import { apiRoutes } from "@/core/api/apiRoutes";

export default function CommercialDocumentsPage() {
  const api = apiRoutes.commercialDocuments;
  const queryClient = useQueryClient();
  const [tab, setTab] = useState("ALL");
  const [customer, setCustomer] = useState({ name: "", contactName: "", email: "", billingAddress: "", phone: "", gstin: "", linkedCompanyId: "" });
  const [message, setMessage] = useState("");
  const [editingCustomerId, setEditingCustomerId] = useState("");
  const [saving, setSaving] = useState(false);
  const customers = useQuery({ queryKey: ["commercial-customers"], queryFn: async () => (await getData(api.customers)).data.data || [] });
  const pureCompanies = useQuery({ queryKey: ["commercial-pure-companies"], queryFn: async () => { const r = await getData(apiRoutes.associateCompany.getAll, { page: 1, limit: 200 }); const value = r.data?.data; return Array.isArray(value) ? value : Array.isArray(value?.data) ? value.data : []; } });
  const docs = useQuery({ queryKey: ["commercial-documents", tab], queryFn: async () => (await getData(api.list, tab === "ALL" ? {} : { type: tab })).data.data || [] });
  function selectPureCompany(id: string) { const c = (pureCompanies.data || []).find((row: any) => String(row._id) === id); if (c) setCustomer({ ...customer, linkedCompanyId: id, name: c.name || "", email: c.email || "", phone: c.phone || "", billingAddress: c.address || "", gstin: c.gstin || "" }); else setCustomer({ ...customer, linkedCompanyId: "" }); }
  async function addCustomer(e: React.FormEvent) { e.preventDefault(); setSaving(true); setMessage(""); try { if (editingCustomerId) await patchData(`${api.customers}/${editingCustomerId}`, customer); else await postData(api.customers, customer); setEditingCustomerId(""); setCustomer({ name: "", contactName: "", email: "", billingAddress: "", phone: "", gstin: "", linkedCompanyId: "" }); await queryClient.invalidateQueries({ queryKey: ["commercial-customers"] }); setMessage("Customer saved."); } catch (error: any) { setMessage(error?.response?.data?.message || "Could not save customer."); } finally { setSaving(false); } }
  return <main className="p-5 md:p-10 space-y-8"><div><h1 className="text-3xl font-bold">Pure Documents</h1><p className="text-default-500">Create quotations and invoices for your customers.</p></div>
    <div className="flex gap-3"><Link className="rounded-xl bg-primary px-5 py-3 text-white font-semibold" href="/dashboard/commercial-documents/new?type=QUOTATION">New quotation</Link><Link className="rounded-xl border border-default-300 px-5 py-3 font-semibold" href="/dashboard/commercial-documents/new?type=INVOICE">New invoice</Link></div>
    <section className="rounded-2xl border border-default-200 p-5"><h2 className="text-xl font-semibold mb-4">Customers</h2><form onSubmit={addCustomer} className="grid md:grid-cols-3 gap-3"><select aria-label="Existing Pure company" value={customer.linkedCompanyId} onChange={e => selectPureCompany(e.target.value)} className="rounded-xl border border-default-300 bg-transparent p-3"><option value="">External customer / choose Pure company</option>{(pureCompanies.data || []).map((c: any) => <option key={c._id} value={c._id}>{c.name}</option>)}</select>{(["name", "contactName", "email", "billingAddress", "phone", "gstin"] as const).map(key => <input key={key} aria-label={key} required={["name", "contactName", "email", "billingAddress"].includes(key)} type={key === "email" ? "email" : "text"} placeholder={key.replace(/([A-Z])/g, " $1")} value={customer[key]} onChange={e => setCustomer({ ...customer, [key]: e.target.value })} className="rounded-xl border border-default-300 bg-transparent p-3" />)}<button disabled={saving} className="rounded-xl bg-primary px-4 py-3 text-white">{editingCustomerId ? "Update customer" : "Save customer"}</button></form>{message && <p role="status" className="mt-3 text-sm">{message}</p>}<div className="mt-5 flex flex-wrap gap-2">{(customers.data || []).map((c: any) => <button type="button" key={c._id} onClick={() => { setEditingCustomerId(c._id); setCustomer({ name: c.name || "", contactName: c.contactName || "", email: c.email || "", billingAddress: c.billingAddress || "", phone: c.phone || "", gstin: c.gstin || "", linkedCompanyId: c.linkedCompanyId || "" }); }} className="rounded-full bg-default-100 px-3 py-1 text-sm">{c.name} · {c.email} · Edit</button>)}</div></section>
    <section><div className="flex gap-2 mb-4">{["ALL", "QUOTATION", "INVOICE"].map(t => <button key={t} onClick={() => setTab(t)} className={`rounded-full px-4 py-2 text-sm ${tab === t ? "bg-primary text-white" : "bg-default-100"}`}>{t === "ALL" ? "All" : t === "QUOTATION" ? "Quotations" : "Invoices"}</button>)}</div>{docs.isLoading ? <p>Loading documents…</p> : docs.isError ? <p>Could not load documents.</p> : <div className="overflow-x-auto rounded-2xl border border-default-200"><table className="w-full text-left text-sm"><thead><tr className="bg-default-100"><th className="p-4">Number</th><th className="p-4">Type</th><th className="p-4">Customer</th><th className="p-4">Total</th><th className="p-4">Status</th></tr></thead><tbody>{(docs.data || []).map((d: any) => <tr key={d._id} className="border-t border-default-200"><td className="p-4"><Link className="text-primary underline" href={`/dashboard/commercial-documents/${d._id}`}>{d.number}</Link></td><td className="p-4">{d.type}</td><td className="p-4">{d.recipient?.name}</td><td className="p-4">{d.currency} {Number(d.total).toFixed(2)}</td><td className="p-4">{d.status}{d.type === "INVOICE" && ` · ${d.paymentStatus}`}</td></tr>)}</tbody></table>{!docs.data?.length && <p className="p-6">No documents yet.</p>}</div>}</section>
  </main>;
}
