"use client";
import React, { useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { getData, postData } from "@/core/api/apiHandler";
import { apiRoutes } from "@/core/api/apiRoutes";
import DocumentSheet from "@/components/dashboard/CommercialDocuments/DocumentSheet";

export default function CommercialDocumentDetail() {
  const { id } = useParams(), router = useRouter(), queryClient = useQueryClient(); const key = String(id || ""), api = apiRoutes.commercialDocuments;
  const [error, setError] = useState(""), [busy, setBusy] = useState(false), [shareUrl, setShareUrl] = useState("");
  const query = useQuery({ queryKey: ["commercial-document", key], queryFn: async () => (await getData(api.getOne(key))).data.data, enabled: Boolean(key) }); const doc = query.data;
  const revisions = useQuery({ queryKey: ["commercial-revisions", key], queryFn: async () => (await getData(`${api.getOne(key)}/revisions`)).data.data || [], enabled: Boolean(key) });
  async function action(name: string, body: any = {}) { setBusy(true); setError(""); try { const result = await postData(api.action(key, name), body); if (result.data.shareUrl) setShareUrl(result.data.shareUrl); await queryClient.invalidateQueries({ queryKey: ["commercial-document", key] }); await queryClient.invalidateQueries({ queryKey: ["commercial-documents"] }); await queryClient.invalidateQueries({ queryKey: ["commercial-revisions", key] }); if (["revise", "to-invoice"].includes(name)) router.push(`/dashboard/commercial-documents/${result.data.data._id}`); } catch (e: any) { setError(e?.response?.data?.message || "Action failed."); } finally { setBusy(false); } }
  const button = (label: string, name: string, body?: any) => <button disabled={busy} onClick={() => action(name, body)} className="rounded-xl border border-default-300 px-4 py-2 text-sm font-semibold">{label}</button>;
  return <main className="p-4 md:p-8"><div className="no-print max-w-[820px] mx-auto mb-5"><Link href="/dashboard/commercial-documents" className="text-primary underline">← Documents</Link>{doc && <div className="flex flex-wrap gap-2 mt-4"><button onClick={() => window.print()} className="rounded-xl bg-primary text-white px-4 py-2 text-sm font-semibold">Print / save PDF</button>{doc.status === "DRAFT" && <Link href={`/dashboard/commercial-documents/new?edit=${key}`} className="rounded-xl border border-default-300 px-4 py-2 text-sm font-semibold">Edit draft</Link>}{doc.status === "DRAFT" && button("Send to customer", "send")}{doc.status === "SENT" && button("Send a new link", "send")}{doc.status !== "DRAFT" && button("Create revision", "revise")}{doc.status === "SENT" && !doc.shareRevokedAt && button("Revoke link", "revoke")}{doc.type === "QUOTATION" && doc.status === "ACCEPTED" && button("Create invoice", "to-invoice")}{doc.type === "INVOICE" && doc.status === "SENT" && button(doc.paymentStatus === "PAID" ? "Mark unpaid" : "Mark paid", "payment", { status: doc.paymentStatus === "PAID" ? "UNPAID" : "PAID" })}</div>}{shareUrl && <div className="mt-3 text-sm break-all">Share link: <a className="text-primary underline" href={shareUrl}>{shareUrl}</a></div>}{error && <p role="alert" className="text-red-600 mt-3">{error}</p>}{(revisions.data || []).length > 1 && <div className="mt-3 text-sm">Versions: {(revisions.data || []).map((r: any) => <Link key={r._id} className="mr-3 text-primary underline" href={`/dashboard/commercial-documents/${r._id}`}>{r.number} (v{r.revision})</Link>)}</div>}{doc?.decidedAt && <p className="mt-3 text-sm">{doc.decision} by {doc.decidedByEmail} on {new Date(doc.decidedAt).toLocaleString()}.</p>}</div>{query.isLoading ? <p>Loading…</p> : query.isError ? <p>Could not load document.</p> : <DocumentSheet doc={doc} />}<style jsx global>{`@media print { nav, aside, .no-print { display: none !important; } body { background: white !important; } .commercial-sheet { max-width: none !important; } @page { size: A4; margin: 16mm; } }`}</style></main>;
}
