"use client";

import Header from "@/components/home/header";
import Footer from "@/components/home/footer";
import ThemedContentWrapper from "@/components/layout/ThemedContentWrapper";
import Link from "next/link";
import { motion } from "framer-motion";
import {
  FiArrowLeft,
  FiArrowRight,
  FiBriefcase,
  FiTrendingUp,
  FiUsers,
  FiShield,
  FiCheckCircle,
  FiXCircle,
  FiZap,
  FiTarget,
  FiLayers,
  FiMap,
  FiAnchor,
  FiCpu,
  FiPieChart,
  FiSearch,
  FiUserCheck,
  FiBookOpen,
  FiClock,
  FiStar,
  FiGlobe
} from "react-icons/fi";
import { buildWebPageJsonLd } from "@/utils/seo";

const webPageJsonLd = buildWebPageJsonLd({
  title: "Operator Role | OBAOL Supreme",
  description:
    "Define the Digital Agro Trader (Operator) role as a system-first execution role without inventory ownership, focused on coordination and completion.",
  path: "/roles/operator",
});

export default function OperatorRolePage() {
  const fadeIn = {
    initial: { opacity: 0, y: 20 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true },
    transition: { duration: 0.6 }
  };

  const workflowSteps = [
    { title: "Identify", desc: "Spot high-intent opportunities in the global agro market.", icon: <FiSearch /> },
    { title: "Verify", desc: "Use OBAOL's system to check counterparty and stock reality.", icon: <FiUserCheck /> },
    { title: "Coordinate", desc: "Manage the layers of logistics, packaging, and audit.", icon: <FiAnchor /> },
    { title: "Complete", desc: "Stay involved until the final settlement is confirmed.", icon: <FiFlag /> }
  ];

  function FiFlag() { return <FiTarget />; } // Placeholder for Flag if needed, using Target

  return (
    <section className="min-h-screen bg-background selection:bg-orange-500/30">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webPageJsonLd) }}
      />
      <Header />

      <ThemedContentWrapper>
        {/* --- HERO SECTION --- */}
        <div className="relative pt-32 md:pt-48 pb-20 md:pb-32 overflow-hidden">
          {/* Background Ambient Effects */}
          <div className="absolute top-0 right-0 -translate-y-1/2 translate-x-1/2 w-[800px] h-[800px] bg-orange-500/10 blur-[150px] rounded-full pointer-events-none" />
          <div className="absolute bottom-0 left-0 translate-y-1/2 -translate-x-1/2 w-[500px] h-[500px] bg-indigo-500/5 blur-[120px] rounded-full pointer-events-none" />

          <div className="container mx-auto max-w-6xl px-4 relative z-10">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="mb-12"
            >
              <Link
                href="/roles"
                className="inline-flex items-center gap-2 text-sm font-bold text-orange-500/80 hover:text-orange-500 transition-all group px-4 py-2 rounded-full border border-orange-500/10 bg-orange-500/5 backdrop-blur-sm mb-12"
              >
                <FiArrowLeft className="group-hover:-translate-x-1 transition-transform" />
                Back to Roles
              </Link>

              <div className="flex flex-col gap-6">
                <motion.div
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  transition={{ delay: 0.2 }}
                  className="inline-flex items-center gap-3 px-4 py-2 rounded-xl bg-orange-500/10 border border-orange-500/20 text-orange-500 w-fit font-bold uppercase tracking-widest text-[10px]"
                >
                  <FiStar className="fill-orange-500" /> Premium Execution Identity
                </motion.div>

                <h1 className="text-4xl md:text-8xl font-black text-foreground tracking-tight leading-[0.95] mb-8">
                  The New Standard of <br />
                  <span className="text-transparent bg-clip-text bg-gradient-to-r from-orange-400 via-orange-500 to-amber-600">
                    Trade Operation.
                  </span>
                </h1>

                <p className="text-xl md:text-3xl text-foreground/70 max-w-4xl leading-relaxed font-medium">
                  We don&apos;t need more brokers. We need <span className="text-foreground">Execution Specialists</span>.
                  Operate in global trades from <span className="text-foreground underline decoration-orange-500/30">anywhere in the world</span> with <span className="text-foreground uppercase italic px-1">Zero Capital</span>.
                </p>
              </div>
            </motion.div>

            {/* Quick Stats Grid */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-24">
              {[
                { icon: <FiZap />, title: "Asset-Light", desc: "No capital required. No stock ownership. Focus purely on execution." },
                { icon: <FiTarget />, title: "Result Driven", desc: "Earnings are generated by completion, not effort or negotiation." },
                { icon: <FiLayers />, title: "System Backed", desc: "Leverage OBAOL's verification and audit trail for every trade." }
              ].map((item, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 30 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.4 + i * 0.1 }}
                  className="p-8 md:p-10 rounded-[2.5rem] bg-content1/40 border border-default-200/50 backdrop-blur-xl hover:border-orange-500/30 transition-all group"
                >
                  <div className="w-14 h-14 rounded-2xl bg-orange-500/10 flex items-center justify-center text-orange-500 mb-8 font-bold group-hover:bg-orange-500 group-hover:text-white transition-all duration-500">
                    {item.icon}
                  </div>
                  <h3 className="text-2xl font-bold text-foreground mb-4 tracking-tight">{item.title}</h3>
                  <p className="text-foreground/50 leading-relaxed font-medium text-lg">
                    {item.title === "Asset-Light" ? "No capital required. Enter the multi-billion dollar agro market with zero inventory." : item.desc}
                  </p>
                </motion.div>
              ))}
            </div>
          </div>
        </div>

        {/* --- GLOBAL ACCESS SECTION (NEW) --- */}
        <div className="py-16 md:py-24 relative overflow-hidden bg-orange-500/[0.03] border-b border-default-100/50">
          <div className="container mx-auto max-w-6xl px-4 text-center">
            <motion.div {...fadeIn} className="space-y-8">
              <div className="mx-auto w-16 h-16 rounded-2xl bg-orange-500/10 flex items-center justify-center text-orange-500 mb-6">
                <FiGlobe size={32} />
              </div>
              <h2 className="text-3xl md:text-5xl font-black text-foreground tracking-tight">
                Operate From <span className="text-orange-500 italic">Anywhere</span> in the World.
              </h2>
              <p className="text-xl text-foreground/60 max-w-3xl mx-auto leading-relaxed font-medium">
                The OBAOL ecosystem is location-independent. Whether you are in Dubai, Mumbai, Lagos, or London, you can orchestrate global agro-trades through our structured execution layer.
              </p>
              <div className="flex flex-wrap justify-center gap-6 mt-12">
                {[
                  "No Geographical Boundaries",
                  "Global Settlement Sync",
                  "Remote Execution Tools",
                  "Cross-Border Compliance"
                ].map((point, i) => (
                  <div key={i} className="px-6 py-3 rounded-2xl bg-background border border-orange-500/20 text-foreground font-bold text-sm shadow-sm hover:border-orange-500 transition-all cursor-default translate-y-0 hover:-translate-y-1">
                    {point}
                  </div>
                ))}
              </div>
            </motion.div>
          </div>
        </div>

        {/* --- IDENTITY & HERITAGE SECTION --- */}
        <div className="py-20 md:py-32 bg-default-50/20 dark:bg-black/20 border-y border-default-100/50 relative overflow-hidden">
          <div className="container mx-auto max-w-6xl px-4">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-24 items-center">
              <motion.div {...fadeIn} className="space-y-12">
                <div className="space-y-4">
                  <h2 className="text-4xl md:text-6xl font-black text-foreground tracking-tight leading-[0.9] md:leading-tight">
                    Who Is An <br />
                    <span className="text-orange-500 italic">Operator?</span>
                  </h2>
                  <p className="text-xl text-foreground/60 leading-relaxed font-medium">
                    This is a role for professionals who understand that trade is 10% discussion and 90% coordination.
                  </p>
                </div>

                {/* Legacy/Expertise Note */}
                <div className="p-8 rounded-3xl bg-orange-500/[0.03] border border-orange-500/10 relative overflow-hidden group">
                  <div className="absolute top-0 right-0 w-32 h-32 bg-orange-500/5 blur-3xl rounded-full" />
                  <h3 className="text-sm font-bold uppercase tracking-widest text-orange-500 mb-4 flex items-center gap-3">
                    <FiAward className="fill-orange-500/20" /> Professional Heritage
                  </h3>
                  <p className="text-foreground/80 font-semibold leading-relaxed mb-4">
                    Specifically designed for <span className="text-foreground underline decoration-orange-500/30">Retired Custom Brokers</span>, <span className="text-foreground underline decoration-orange-500/30">Logistics Pros</span>, and <span className="text-foreground underline decoration-orange-500/30">Industry Veterans</span>.
                  </p>
                  <p className="text-sm text-foreground/50 leading-relaxed">
                    Your years of experience in cross-border trade, compliance, and documentation are the most valuable assets in the OBAOL ecosystem.
                  </p>
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                  {[
                    "Opportunity Identifiers",
                    "Relationship Architects",
                    "Coordination Experts",
                    "Completion Specialists"
                  ].map((text, i) => (
                    <div key={i} className="flex items-center gap-4 text-foreground/80 font-bold group">
                      <div className="w-10 h-10 rounded-xl bg-orange-500/10 flex items-center justify-center text-orange-500 group-hover:bg-orange-500 group-hover:text-white transition-all">
                        <FiCheckCircle size={18} />
                      </div>
                      {text}
                    </div>
                  ))}
                </div>
              </motion.div>

              {/* Visual Interactive Element */}
              <motion.div
                initial={{ opacity: 0, x: 50, filter: 'blur(10px)' }}
                whileInView={{ opacity: 1, x: 0, filter: 'blur(0px)' }}
                viewport={{ once: true }}
                className="relative p-1 bg-gradient-to-br from-orange-500/20 to-transparent rounded-[4rem]"
              >
                <div className="bg-background rounded-[3.8rem] p-8 md:p-16 border border-default-100 relative overflow-hidden">
                  <div className="absolute top-0 right-0 w-64 h-64 bg-orange-500/5 blur-[100px] rounded-full" />

                  <div className="space-y-12 relative z-10">
                    <div className="text-center space-y-2">
                      <span className="text-[10px] font-bold tracking-[0.5em] uppercase text-foreground/30">The Operator Pulse</span>
                      <div className="h-1 w-24 bg-orange-500/30 mx-auto rounded-full" />
                    </div>

                    <div className="space-y-8">
                      <div className="flex items-center gap-6 p-6 rounded-2xl bg-content2/50 border border-red-500/10 group grayscale hover:grayscale-0 transition-all duration-700">
                        <FiXCircle className="text-red-500 text-3xl" />
                        <div>
                          <div className="font-bold text-foreground/40 group-hover:text-foreground/80 line-through">Passive Lead Forwarding</div>
                          <div className="text-xs text-foreground/20 group-hover:text-red-500/50 uppercase font-black tracking-widest mt-1">Inefficient</div>
                        </div>
                      </div>

                      <div className="w-full flex justify-center py-4">
                        <motion.div
                          animate={{ y: [0, 10, 0] }}
                          transition={{ repeat: Infinity, duration: 2 }}
                          className="w-px h-12 bg-gradient-to-b from-orange-500/50 to-transparent"
                        />
                      </div>

                      <div className="flex items-center gap-6 p-8 rounded-3xl bg-orange-500 shadow-[0_20px_50px_-10px_rgba(245,165,36,0.3)] border border-orange-400 group relative">
                        <div className="absolute -inset-1 bg-white/10 blur-xl opacity-0 group-hover:opacity-100 transition-opacity" />
                        <FiZap className="text-white text-4xl animate-pulse" />
                        <div className="relative z-10">
                          <div className="font-black text-white text-xl tracking-tight leading-none">Active Execution</div>
                          <div className="text-[10px] text-white/70 uppercase font-black tracking-[0.2em] mt-2">The OBAOL Standard</div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </motion.div>
            </div>
          </div>
        </div>

        {/* --- PERFORMANCE ROADMAP (NEW) --- */}
        <div className="py-20 md:py-32 container mx-auto max-w-7xl px-4">
          <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-8 mb-16 md:mb-24">
            <div className="max-w-2xl space-y-4 text-left">
              <h2 className="text-4xl md:text-6xl font-black text-foreground tracking-tight">The <span className="text-orange-500">Execution</span> Roadmap.</h2>
              <p className="text-xl text-foreground/50 font-medium leading-relaxed">How a single trade moves from identification to confirmed settlement within our system.</p>
            </div>
            <div className="px-6 py-3 rounded-full border border-orange-500/20 bg-orange-500/5 text-orange-500 font-bold uppercase tracking-widest text-[10px]">
              4 Key Milestones
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-12 relative">
            {/* Connection Line */}
            <div className="hidden md:block absolute top-[28px] left-[10%] right-[10%] h-[1px] bg-gradient-to-r from-orange-500/0 via-orange-500/20 to-orange-500/0 z-0" />

            {workflowSteps.map((step, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
                viewport={{ once: true }}
                className="relative z-10 space-y-6"
              >
                <div className="w-14 h-14 rounded-full bg-background border-2 border-orange-500/30 flex items-center justify-center text-orange-500 text-xl font-bold shadow-2xl">
                  {step.icon}
                </div>
                <h4 className="text-2xl font-bold text-foreground tracking-tight">{step.title}</h4>
                <p className="text-foreground/50 leading-relaxed font-medium">{step.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>

        {/* --- PERFORMANCE-BASED EARNINGS --- */}
        <div className="py-20 md:py-32 bg-foreground dark:bg-neutral-900 rounded-[3rem] md:rounded-[5rem] mx-4 my-8 text-background dark:text-foreground relative overflow-hidden">
          {/* Subtle patterns */}
          <div className="absolute inset-0 opacity-10 pointer-events-none" style={{ backgroundImage: 'radial-gradient(circle at 2px 2px, white 1px, transparent 0)', backgroundSize: '40px 40px' }} />

          <div className="container mx-auto max-w-6xl px-4 relative z-10">
            <div className="text-center mb-16 md:mb-24 space-y-6">
              <h2 className="text-4xl md:text-7xl font-black tracking-tight leading-none text-white">Controlled Clarity.</h2>
              <p className="text-xl text-white/50 max-w-2xl mx-auto font-medium tracking-wide italic">Earnings are generated exclusively from completion. No completion, no commission.</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
              <motion.div {...fadeIn} className="p-8 md:p-10 rounded-[2.5rem] md:rounded-[3rem] bg-white/[0.03] border border-white/10 backdrop-blur-xl">
                <h3 className="text-2xl md:text-3xl font-black text-white mb-8 md:mb-10 border-b border-white/10 pb-6 flex items-center gap-4">
                  <FiPieChart className="text-orange-500" /> Revenue Source
                </h3>
                <div className="space-y-8">
                  {[
                    { label: "Deal Execution", sub: "Closing the final trade", val: "Major Pool Share" },
                    { label: "Supplier Ownership", sub: "Managing verified sources", val: "Recurring Flow" },
                    { label: "Handling", sub: "Managing successful orders & enquiries", val: "Rating Based" },
                    { label: "Leadership", sub: "Mentoring & growing operators", val: "Tiered Share" }
                  ].map((item, i) => (
                    <div key={i} className="flex justify-between items-start group">
                      <div>
                        <div className="font-bold text-white text-xl mb-1">{item.label}</div>
                        <div className="text-white/40 font-medium">{item.sub}</div>
                      </div>
                      <div className="px-4 py-1.5 rounded-full bg-orange-500 text-white font-black text-[10px] uppercase tracking-widest">{item.val}</div>
                    </div>
                  ))}
                </div>
              </motion.div>

              <motion.div {...fadeIn} className="p-8 md:p-10 rounded-[2.5rem] md:rounded-[3rem] bg-red-500/[0.02] border border-red-500/20 flex flex-col justify-between">
                <div className="mb-8 md:mb-0">
                  <h3 className="text-2xl md:text-3xl font-black text-white mb-8 md:mb-10 border-b border-red-500/20 pb-6 flex items-center gap-4">
                    <FiXCircle className="text-red-500" /> Non-Earning
                  </h3>
                  <div className="space-y-6">
                    {["Initial Enquiries", "Long Negotiations", "Partial Progress", "Static Lead Sharing"].map((item, i) => (
                      <div key={i} className="flex items-center gap-4 text-white/30 line-through font-bold text-lg">
                        <div className="w-2 h-2 rounded-full bg-red-500/30" />
                        {item}
                      </div>
                    ))}
                  </div>
                </div>
                <div className="mt-12 p-8 rounded-3xl bg-red-500/5 text-red-500/80 text-base italic font-bold leading-relaxed border border-red-500/10">
                  &quot;Efficiency is rewarded. Effort is expected. Completion is what creates value.&quot;
                </div>
              </motion.div>
            </div>

            <div className="mt-20 text-center">
              <Link
                href="/commission-structure"
                className="group inline-flex items-center gap-4 px-10 py-5 rounded-[2rem] bg-white/10 text-white font-black text-xl hover:bg-white/20 transition-all border border-white/10 shadow-2xl"
              >
                View Detailed Commission Structure
                <FiArrowRight className="transition-transform group-hover:translate-x-3" />
              </Link>
            </div>
          </div>
        </div>

        {/* --- PATHWAYS --- */}
        <div className="py-20 md:py-32 container mx-auto max-w-6xl px-4">
          <div className="text-center mb-16 md:mb-24 space-y-4">
            <h2 className="text-4xl md:text-6xl font-black text-foreground tracking-tight">Two Pathways. One Goal.</h2>
            <p className="text-xl text-foreground/50 font-medium">Choose how you want to integrate into the OBAOL ecosystem.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-16">
            {/* Independent */}
            <motion.div
              whileHover={{ y: -10 }}
              className="p-8 md:p-12 rounded-[3rem] md:rounded-[4rem] bg-content1 shadow-sm border border-default-200 relative overflow-hidden group flex flex-col min-h-[400px] md:min-h-[500px]"
            >
              <div className="absolute top-0 right-0 p-8">
                <div className="w-16 h-16 rounded-[2rem] bg-default-50 flex items-center justify-center text-default-400 font-bold group-hover:scale-110 group-hover:bg-orange-500 group-hover:text-white transition-all duration-500">
                  <FiBriefcase size={32} />
                </div>
              </div>

              <div className="mt-12 md:mt-20 flex-grow space-y-8 text-left">
                <div className="space-y-4">
                  <h3 className="text-3xl md:text-4xl font-black text-foreground leading-none">Independent <br /> Operator</h3>
                  <p className="text-foreground/50 leading-relaxed font-bold text-base md:text-lg">For the self-starters and existing network owners.</p>
                </div>

                <div className="space-y-4">
                  {[
                    "Maintain your own relationship network",
                    "Self-driven trade coordination",
                    "Use OBAOL for verification & audit",
                    "Manage your own completion timeline"
                  ].map((item, i) => (
                    <div key={i} className="flex items-center gap-3 text-sm font-bold text-foreground/70">
                      <FiCheckCircle className="text-orange-500 shrink-0" />
                      {item}
                    </div>
                  ))}
                </div>
              </div>

              <div className="mt-12 pt-8 border-t border-default-100 flex items-baseline gap-4">
                <span className="text-[10px] font-black uppercase tracking-[0.3em] text-orange-500/60">Category</span>
                <span className="text-foreground font-black tracking-tight italic">Industry Veteran / Experienced</span>
              </div>
            </motion.div>

            {/* Team-Based */}
            <motion.div
              whileHover={{ y: -10 }}
              className="p-8 md:p-12 rounded-[3rem] md:rounded-[4rem] bg-orange-500 text-white relative overflow-hidden group flex flex-col min-h-[400px] md:min-h-[500px] shadow-2xl shadow-orange-500/30 border border-orange-400"
            >
              <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-white/10 blur-[100px] rounded-full -translate-y-1/2 translate-x-1/2 pointer-events-none" />

              <div className="absolute top-0 right-0 p-8">
                <div className="w-16 h-16 rounded-[2rem] bg-white/20 backdrop-blur-md flex items-center justify-center text-white font-bold group-hover:scale-110 group-hover:bg-white group-hover:text-orange-600 transition-all duration-500">
                  <FiUsers size={32} />
                </div>
              </div>

              <div className="mt-12 md:mt-20 flex-grow space-y-8 relative z-10 text-left">
                <div className="space-y-4">
                  <h3 className="text-3xl md:text-4xl font-black text-white leading-none">Team-Based <br /> Operator</h3>
                  <p className="text-white/80 leading-relaxed font-bold text-base md:text-lg">For those building their legacy within a structure.</p>
                </div>

                <div className="space-y-4">
                  {[
                    "Operate within internal workflow layers",
                    "Collaborative execution with senior pros",
                    "Direct capability building roadmap",
                    "Focus on specific trade segments"
                  ].map((item, i) => (
                    <div key={i} className="flex items-center gap-3 text-sm font-bold text-white">
                      <FiCheckCircle className="text-white shrink-0" />
                      {item}
                    </div>
                  ))}
                </div>
              </div>

              <div className="mt-12 pt-8 border-t border-white/20 flex items-baseline gap-4 relative z-10">
                <span className="text-[10px] font-black uppercase tracking-[0.3em] text-white/50">Category</span>
                <span className="text-white font-black tracking-tight italic">Builder / Capability Focused</span>
              </div>
            </motion.div>
          </div>
        </div>

        {/* --- THE EXECUTION TOOLKIT (NEW) --- */}
        <div className="py-20 md:py-32 bg-default-50/10 relative overflow-hidden">
          <div className="container mx-auto max-w-6xl px-4 text-center">
            <h2 className="text-4xl md:text-6xl font-black text-foreground tracking-tight mb-12 md:mb-20 text-left md:text-center">Tools of The Operator.</h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-8">
              {[
                { icon: <FiCpu />, label: "Verification Engine" },
                { icon: <FiPieChart />, label: "Completion Tracking" },
                { icon: <FiClock />, label: "Audit Timeline" },
                { icon: <FiMap />, label: "Trade Topology" },
                { icon: <FiBookOpen />, label: "Legacy Knowledge" },
                { icon: <FiUsers />, label: "Counterparty Radar" },
                { icon: <FiShield />, label: "Compliance Filter" },
                { icon: <FiAnchor />, label: "Logistics Node" }
              ].map((tool, i) => (
                <motion.div
                  key={i}
                  whileHover={{ scale: 1.05, y: -5 }}
                  className="p-6 md:p-8 rounded-3xl bg-content1 border border-default-200 shadow-sm flex flex-col items-center gap-4 group hover:border-orange-500/30 transition-all"
                >
                  <div className="text-3xl text-orange-500/50 group-hover:text-orange-500 transition-colors">{tool.icon}</div>
                  <span className="text-sm font-bold text-foreground/60 group-hover:text-foreground tracking-tight">{tool.label}</span>
                </motion.div>
              ))}
            </div>
          </div>
        </div>

        {/* --- FINAL CTA --- */}
        <div className="py-24 md:py-40 container mx-auto max-w-5xl px-4 text-center">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            whileInView={{ opacity: 1, scale: 1 }}
            viewport={{ once: true }}
            className="p-10 md:p-32 rounded-[3.5rem] md:rounded-[5rem] bg-content1 border-2 border-orange-500/20 shadow-2xl relative overflow-hidden group"
          >
            {/* Ambient glow */}
            <div className="absolute top-0 left-1/2 -translate-x-1/2 w-96 h-96 bg-orange-500/10 blur-[120px] rounded-full pointer-events-none group-hover:bg-orange-500/20 transition-all duration-1000" />

            <div className="relative z-10 space-y-12">
              <div className="space-y-6">
                <h2 className="text-5xl md:text-8xl font-black text-foreground tracking-tight leading-[0.9]">Ready to Step Into <br /> Your Role?</h2>
                <p className="text-xl md:text-2xl text-foreground/50 max-w-3xl mx-auto font-medium leading-relaxed italic">
                  Operator is not a position we assign. It is a role you define by the trades you complete within the system.
                </p>
              </div>

              <div className="flex flex-col md:flex-row justify-center gap-6 md:gap-8">
                <Link
                  href="/auth/operator/register"
                  className="group relative inline-flex justify-center items-center gap-4 md:gap-6 px-10 md:px-14 py-5 md:py-7 rounded-full bg-orange-500 text-white font-black text-xl shadow-[0_25px_80px_-15px_rgba(245,165,36,0.5)] hover:bg-orange-600 hover:scale-[1.05] active:scale-[0.98] transition-all"
                >
                  Start Operator Entry
                  <FiArrowRight size={24} className="transition-transform group-hover:translate-x-3" />
                </Link>
                
                <Link
                  href="/commission-structure"
                  className="group relative inline-flex justify-center items-center gap-4 px-10 py-5 rounded-full bg-content2 text-foreground font-black text-lg border-2 border-default-200 hover:border-orange-500/50 hover:bg-content3 hover:scale-[1.05] active:scale-[0.98] transition-all"
                >
                  Commission Structure
                  <FiArrowRight size={20} className="text-orange-500 transition-transform group-hover:translate-x-2" />
                </Link>
              </div>
            </div>
          </motion.div>
        </div>
      </ThemedContentWrapper>
      <Footer />
    </section>
  );
}

function FiAward({ className }: { className?: string }) {
  return <FiShield className={className} />;
}
function FiFlag() {
  return <FiTarget />;
}
