"use client";
import {
  activityFileRoutes,
  activityRoutes,
  activityStatusRoutes,
  activityTypeRoutes,
  adminRoutes,
  associateCompanyRoutes,
  associateRoutes,
  categoryRoutes,
  certificationRoutes,
  companyBusinessModelRoutes,
  companyFunctionRoutes,
  companySubFunctionRoutes,
  companyStageRoutes,
  companyTypeRoutes,
  catalogItemRoutes,
  catalogRoutes,
  designationRoutes,
  displayedRateRoutes,
  operatorRoutes,
  enquiryProcessStatusRoutes,
  enquiryRoutes,
  generalIntentRoutes,
  incotermRoutes,
  inventoryManagerRoutes,
  inventoryRoutes,
  jobRoleRoutes,
  jobTypeRoutes,
  languageRoutes,
  paymentTermRoutes,
  productRoutes,
  productVariantRoutes,
  projectManagerRoutes,
  projectRoutes,
  projectStatusRoutes,
  projectTypeRoutes,
  researchedCompanyRoutes,
  serviceCompanyRoutes,
  subCategoryRoutes,
  subIntentRoutes,
  timeSheetRoutes,
  variantRateRoutes,
  workerRoutes,
  warehouseRoutes,
} from "@/core/api/apiRoutes";
import { fetchDependentOptions } from "./fetchDependentOptions";

// Helper function to generate columns based on the current table
export const generateColumns = (currentTable: string, tableConfig: any, userRole?: string) => {
  const roleLower = String(userRole || "").toLowerCase();
  // Filter out the "Actions" column initially
  let nonActionColumns = tableConfig[currentTable]
    .filter(
      (field: any) =>
        field.inTable && field.type !== "select" && field.key !== "actions2"
    )
    .filter((field: any) => {
      // Hide commission/finalRate from non-admins except CatalogItem where associates need margin visibility.
      if (roleLower !== "admin" && (field.key === "commission" || field.key === "finalRate")) {
        if (currentTable === "catalogItem" && field.key === "commission") {
          return true;
        }
        return false;
      }
      return true;
    })
    .map((field: any) => ({
      name: field.label.toUpperCase(),
      uid: field.key,
      type: field.type,
    }));

  if (currentTable === "associate") {
    nonActionColumns.push({ name: "COMPANY", uid: "associateCompany" });
    nonActionColumns.push({ name: "DESIGNATION", uid: "designation" });
  }
  if (currentTable === "associateCompany") {
    nonActionColumns.push({ name: "LOCATION", uid: "location" });
    nonActionColumns.push({ name: "COMPANY TYPE", uid: "companyType" });
  } else if (currentTable === "projects") {
    // nonActionColumns.push({ name: "Admin Name", uid: "adminName" });
    nonActionColumns.push({
      name: "Project Manager",
      uid: "projectManagerName",
    });
    nonActionColumns.push({ name: "ProjectStatus", uid: "projectStatus" });
    nonActionColumns.push({ name: "Project Type", uid: "projectType" });
    nonActionColumns.push({ name: "Location", uid: "location" });
  } else if (currentTable === "activity") {
    // nonActionColumns.push({ name: "Admin Name", uid: "adminName" });
    nonActionColumns.push({
      name: "Activity Manager",
      uid: "activityManagerName",
    });
    nonActionColumns.push({ name: "Activity Status", uid: "activityStatus" });
    nonActionColumns.push({ name: "Activity Type", uid: "activityType" });
  } else if (currentTable === "variantRate") {
    if (roleLower === "admin") {
      nonActionColumns.push({ name: "Associate", uid: "associate" });
    }
    nonActionColumns.push({ name: "Product", uid: "productVariant", maxWidth: "max-w-[260px]" });
  } else if (currentTable === "displayedRate" || currentTable === "catalogItem") {
    if (userRole !== "Associate") {
      nonActionColumns.push({ name: "Associate", uid: "associate" });
    }
    nonActionColumns.push({ name: "Product", uid: "product" });
  } else if (
    currentTable === "projectManager" ||
    currentTable === "activityManager"
  ) {
    nonActionColumns.push({ name: "ADMIN", uid: "admin" });
  } else if (currentTable === "inventories") {
    nonActionColumns.push({ name: "Product", uid: "product", maxWidth: "max-w-[240px]" });
    nonActionColumns.push({ name: "Product Variant", uid: "productVariant", maxWidth: "max-w-[240px]" });
    if (roleLower === "admin") {
      nonActionColumns.push({ name: "Associate", uid: "associate" });
    }
  }

  // Find the "Actions" column separately
  const actionsColumn = tableConfig[currentTable].find(
    (field: any) => field.type === "action" && field.inTable
  );

  // Append the "Actions" column at the end
  if (actionsColumn) {
    nonActionColumns.push({
      name: actionsColumn.label.toUpperCase(),
      uid: actionsColumn.key,
      type: actionsColumn.type,
    });
  }

  return nonActionColumns;
};

export const apiRoutesByRole: Record<string, string> = {
  admin: adminRoutes.getAll,
  inventoryManager: inventoryManagerRoutes.getAll,
  projectManager: projectManagerRoutes.getAll,
  worker: workerRoutes.getAll,
  projectType: projectTypeRoutes.getAll,
  serviceCompany: serviceCompanyRoutes.getAll,
  projectStatus: projectStatusRoutes.getAll,
  projects: projectRoutes.getAll,
  activity: activityRoutes.getAll,
  activityType: activityTypeRoutes.getAll,
  activityStatus: activityStatusRoutes.getAll,
  timeSheet: timeSheetRoutes.getAll,
  activityFile: activityFileRoutes.getAll,
  associateCompany: associateCompanyRoutes.getAll,
  associate: associateRoutes.getAll,
  operator: operatorRoutes.getAll,
  category: categoryRoutes.getAll,
  subCategory: subCategoryRoutes.getAll,
  product: productRoutes.getAll,
  productVariant: productVariantRoutes.getAll,
  variantRate: variantRateRoutes.getAll,
  displayedRate: displayedRateRoutes.getAll,
  catalogItem: catalogItemRoutes.getAll,
  enquiry: enquiryRoutes.getAll,
  enquiryProcessStatus: enquiryProcessStatusRoutes.getAll,
  incoterm: incotermRoutes.getAll,
  paymentTerm: paymentTermRoutes.getAll,
  designation: designationRoutes.getAll,
  companyType: companyTypeRoutes.getAll,
  certification: certificationRoutes.getAll,
  companyBusinessModel: companyBusinessModelRoutes.getAll,
  companyFunction: companyFunctionRoutes.getAll,
  companySubFunction: companySubFunctionRoutes.getAll,
  generalIntent: generalIntentRoutes.getAll,
  subIntent: subIntentRoutes.getAll,
  companyStage: companyStageRoutes.getAll,
  researchedCompany: researchedCompanyRoutes.getAll,
  jobRole: jobRoleRoutes.getAll,
  jobType: jobTypeRoutes.getAll,
  language: languageRoutes.getAll,
  inventories: inventoryRoutes.getAll,
  warehouse: warehouseRoutes.getAll,
};

export const initialTableConfig: Record<
  any,
  {
    label: string;
    type:
    | "text"
    | "select"
    | "multiselect"
    | "multiselectValue"
    | "file"
    | "textarea"
    | "boolean"
    | "image"
    | "action"
    | "email"
    | "date"
    | "number"
    | "time"
    | "multiTime"
    | "multiTimeRange"
    | "link"
    | "dateTime"
    | "password"
    | "week"; // Define specific types

    filterType?:
    | "text"
    | "select"
    | "multiselect"
    | "boolean"
    | "date"
    | "range";
    key: string;
    inForm: boolean;
    inTable: boolean;
    dynamicValuesFn?: any;
    inEdit?: boolean;
    dependsOn?: string;
    values?: { key: string; value: string }[];
    accept?: string;
    required?: boolean;
    showWhen?: { key: string; equals: any[] };
  }[]
> = {
  // Start of User
  admin: [
    {
      label: "Name",
      type: "text",
      filterType: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Email",
      type: "email",
      filterType: "text",
      key: "email",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Password",
      type: "password",
      key: "password",
      inForm: true,
      inTable: false,
      inEdit: false,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  operator: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Phone Number",
      type: "number",
      key: "phone",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "email",
      type: "email",
      key: "email",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Password",
      type: "password",
      key: "password",
      inForm: true,
      inTable: false,
      inEdit: false,
      required: true,
    },

    {
      label: "Address",
      type: "text",
      key: "address",
      inEdit: true,
      inForm: true,
      inTable: false,
      required: true,
    },
    {
      label: "State",
      type: "select",
      filterType: "select",
      key: "state",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("state"),
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "District",
      type: "select",
      key: "district",
      filterType: "select",
      dependsOn: "state",
      values: [],
      dynamicValuesFn: (stateId: string) =>
        fetchDependentOptions("district", "state", stateId),
      inEdit: true,
      inForm: true,
      inTable: true,
      required: true,
    },

    {
      label: "Joining Date",
      type: "date",
      key: "joiningDate",
      inEdit: true,
      inForm: true,
      inTable: false,
      required: true,
    },

    {
      label: "Job Type",
      type: "select",
      filterType: "select",
      key: "jobType",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("jobType"),
      inForm: false,
      inEdit: false,
      inTable: false,
      required: false,
    },
    {
      label: "Job Role",
      type: "select",
      filterType: "select",
      key: "jobRole",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("jobRole"),
      inForm: false,
      inEdit: false,
      inTable: false,
      required: false,
    },
    {
      label: "Mentor Operator",
      type: "select",
      filterType: "select",
      key: "mentorOperator",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("operator"),
      inForm: true,
      inEdit: true,
      inTable: false,
      required: false,
    },

    {
      label: "Language Known",
      type: "multiselect",
      filterType: "select",
      key: "languageKnown",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("language"),
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Presence",
      type: "text",
      key: "presenceStatus",
      inForm: false,
      inEdit: false,
      inTable: true,
    },
    {
      label: "Last Seen",
      type: "text",
      key: "lastSeenAt",
      inForm: false,
      inEdit: false,
      inTable: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  inventoryManager: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Email",
      type: "email",
      key: "email",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Password",
      type: "password",
      key: "password",
      inForm: true,
      inTable: false,
      inEdit: false,
      required: true,
    },

    {
      label: "Admin",
      type: "select",
      key: "admin",
      values: [], // We'll populate this dynamically
      dynamicValuesFn: () => fetchDependentOptions("admin"),
      inEdit: true,
      inForm: true,
      inTable: false,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  associate: [
    {
      label: "Associate Name",
      type: "text",
      key: "name",
      filterType: "text",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Email",
      type: "email",
      key: "email",
      filterType: "text",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Phone",
      type: "number",
      key: "phone",
      inForm: true,
      filterType: "text",
      inTable: true,
      inEdit: true,
      required: true,
    },
    {
      label: "Phone Secondary",
      type: "number",
      key: "phoneSecondary",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Designation",
      type: "select",
      filterType: "select",
      key: "designation",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("designation"),
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Associate Company",
      type: "select",
      key: "associateCompany",
      filterType: "select",
      values: [],
      dynamicValuesFn: () =>
        fetchDependentOptions("associateCompany", undefined, undefined, {
          mode: "associateForm",
        }),
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Account Active",
      type: "boolean",
      key: "isActive",
      filterType: "select",
      inForm: false,
      inEdit: true,
      inTable: true,
    },
    {
      label: "Company Verified",
      type: "boolean",
      key: "isCompanyVerified",
      filterType: "select",
      inForm: false,
      inEdit: true,
      inTable: true,
    },
    {
      label: "Email Verified",
      type: "boolean",
      key: "isEmailVerified",
      filterType: "select",
      inForm: false,
      inEdit: true,
      inTable: true,
    },
    {
      label: "Registration Status",
      type: "text",
      key: "registrationStatus",
      filterType: "text",
      inForm: false,
      inEdit: true,
      inTable: true,
    },
    {
      label: "Contact Preference",
      type: "text",
      key: "onboardingContactPreference",
      filterType: "text",
      inForm: false,
      inEdit: true,
      inTable: true,
    },
    {
      label: "Presence",
      type: "text",
      key: "presenceStatus",
      inForm: false,
      inEdit: false,
      inTable: true,
    },
    {
      label: "Last Seen",
      type: "text",
      key: "lastSeenAt",
      inForm: false,
      inEdit: false,
      inTable: true,
    },
    {
      label: "Password",
      type: "password",
      key: "password",
      inForm: true,
      inEdit: false,
      inTable: false,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],

  worker: [
    {
      label: "Worker Name",
      type: "text",
      key: "name",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Password",
      type: "password",
      key: "password",
      inForm: true,
      inEdit: false,
      inTable: false,
      required: true,
    },
    {
      label: "Email",
      type: "email",
      key: "email",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Skill",
      type: "text",
      key: "skill",
      inForm: true,
      inTable: true,
    },
    {
      label: "Service Company",
      type: "select",
      key: "serviceCompany",
      values: [], // We'll populate this dynamically
      inForm: true,
      inTable: true,
      inEdit: true,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  designation: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  jobRole: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  jobType: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  language: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Country",
      type: "select",
      filterType: "select",
      key: "country",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("country"),
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  // End of User

  // Start of Company & Essentials
  associateCompany: [
    {
      label: "Company Name",
      type: "text",
      key: "name",
      filterType: "text",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Email",
      type: "email",
      key: "email",
      filterType: "text",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Phone",
      type: "number",
      filterType: "text",
      key: "phone",
      inForm: true,
      inTable: true,
      required: true,
    },
    // {
    //   label: "Location",
    //   type: "select",
    //   key: "location",
    //   values: [],
    //   inForm: true,
    //   inTable: true,
    //   required: true,
    // },
    {
      label: "Company Type",
      type: "select",
      filterType: "select",
      key: "companyType",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("companyType"),
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "State",
      type: "select",
      filterType: "select",
      key: "state",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("state"),
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "District",
      type: "select",
      key: "district",
      filterType: "select",
      dependsOn: "state",
      values: [],
      dynamicValuesFn: (stateId: string) =>
        fetchDependentOptions("district", "state", stateId),
      inEdit: true,
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Division",
      type: "select",
      filterType: "select",
      key: "division",
      dependsOn: "district", // 👈
      dynamicValuesFn: (districtId: string) =>
        fetchDependentOptions("division", "district", districtId),
      values: [],
      inEdit: true,
      inForm: true,
      inTable: true,
    },
    {
      label: "Pin Code ",
      type: "select",
      filterType: "select",
      key: "pincodeEntry",
      dependsOn: "division", // 👈
      dynamicValuesFn: (divisionId: string) =>
        fetchDependentOptions("pincodeEntry", "division", divisionId),
      values: [],
      inEdit: true,
      inForm: true,
      inTable: true,
    },
    {
      label: "Phone Secondary",
      type: "number",
      key: "phoneSecondary",
      inEdit: true,
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Service Capabilities",
      type: "multiselect",
      key: "serviceCapabilities",
      values: [
        { key: "PROCUREMENT", value: "Procurement" },
        { key: "CERTIFICATION", value: "Certification" },
        { key: "TRANSPORTATION", value: "Transportation" },
        { key: "SHIPPING", value: "Freight Forwarding & Shipping" },
        { key: "PACKAGING", value: "Packaging" },
        { key: "QUALITY_TESTING", value: "Quality Testing & Assurance" },
      ],
      inEdit: true,
      inForm: true,
      inTable: true,
    },
    {
      label: "Assigned Overseer",
      type: "select",
      key: "assignedOperator",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("operator"),
      inForm: true,
      inEdit: true,
      inTable: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  researchedCompany: [
    {
      label: "Submitted By",
      type: "select",
      filterType: "select",
      key: "submittedByOperator",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("operator"),
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Company Name",
      type: "text",
      key: "name",
      filterType: "text",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Email",
      type: "email",
      key: "email",
      filterType: "text",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Phone",
      type: "number",
      filterType: "text",
      key: "phone",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Phone Secondary",
      type: "number",
      key: "phoneSecondary",
      inEdit: true,
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Products",
      type: "multiselect",
      filterType: "text",
      key: "product",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("product"),
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },

    {
      label: "Certifications",
      type: "multiselect",
      filterType: "text",
      key: "certification",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("certification"),
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },

    {
      label: "Business Model",
      type: "multiselect",
      filterType: "select",
      key: "companyBusinessModel",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("companyBusinessModel"),
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Company Type",
      type: "select",
      filterType: "select",
      key: "companyType",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("companyType"),
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Company Stage",
      type: "select",
      filterType: "select",
      key: "companyStage",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("companyStage"),
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Company Intent",
      type: "multiselect",
      filterType: "select",
      key: "companyIntent",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("subIntent"),
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    // {
    //   label: "Role",
    //   type: "text",
    //   filterType: "text",
    //   key: "role",
    //   inForm: true,
    //   inTable: true,
    //   required: true,
    // },

    {
      label: "Pain Points",
      type: "text",
      filterType: "text",
      key: "painPoints",
      inForm: true,
      inTable: true,
      required: true,
    },
    // {
    //   label: "Location",
    //   type: "select",
    //   key: "location",
    //   values: [],
    //   inForm: true,
    //   inTable: true,
    //   required: true,
    // },

    {
      label: "State",
      type: "select",
      filterType: "select",
      key: "state",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("state"),
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "District",
      type: "select",
      key: "district",
      filterType: "select",
      dependsOn: "state",
      values: [],
      dynamicValuesFn: (stateId: string) =>
        fetchDependentOptions("district", "state", stateId),
      inEdit: true,
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Division",
      type: "select",
      filterType: "select",
      key: "division",
      dependsOn: "district", // 👈
      dynamicValuesFn: (districtId: string) =>
        fetchDependentOptions("division", "district", districtId),
      values: [],
      inEdit: true,
      inForm: true,
      inTable: true,
    },
    {
      label: "Pin Code ",
      type: "select",
      filterType: "select",
      key: "pincodeEntry",
      dependsOn: "division", // 👈
      dynamicValuesFn: (divisionId: string) =>
        fetchDependentOptions("pincodeEntry", "division", divisionId),
      values: [],
      inEdit: true,
      inForm: true,
      inTable: true,
    },

    {
      label: "Website Link",
      type: "link",
      filterType: "text",
      key: "websiteLink",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  companyType: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  certification: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  companyBusinessModel: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  companyFunction: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Slug",
      type: "text",
      key: "slug",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: false,
    },
    {
      label: "Sub-Functions",
      type: "number",
      key: "subFunctionCount",
      inForm: false,
      inEdit: false,
      inTable: true,
      required: false,
    },
    {
      label: "Order",
      type: "number",
      key: "orderIndex",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: false,
    },
    {
      label: "Active",
      type: "boolean",
      key: "isActive",
      filterType: "select",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: false,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  companySubFunction: [
    {
      label: "Function",
      type: "select",
      key: "functionId",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("companyFunction"),
      inForm: true,
      inEdit: true,
      inTable: false,
      required: true,
    },
    {
      label: "Function",
      type: "text",
      key: "functionName",
      inForm: false,
      inEdit: false,
      inTable: true,
      required: false,
    },
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Slug",
      type: "text",
      key: "slug",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: false,
    },
    {
      label: "Order",
      type: "number",
      key: "orderIndex",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: false,
    },
    {
      label: "Active",
      type: "boolean",
      key: "isActive",
      filterType: "select",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: false,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  generalIntent: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  subIntent: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "General Intent",
      type: "select",
      filterType: "select",
      key: "generalIntent",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("generalIntent"),
      inForm: true,
      inTable: false,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  companyStage: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Description",
      type: "text",
      key: "description",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },

    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  // End of Company & Essentials

  incoterm: [
    {
      label: "Code",
      type: "text",
      key: "code",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inEdit: true,
      inTable: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],

  paymentTerm: [
    {
      label: "Label",
      type: "text",
      key: "label",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Applicable Incoterms",
      type: "text",
      key: "applicableIncoterms",
      inForm: true,
      inEdit: true,
      inTable: true,
      placeholder: "EXW, FOB, CIF",
    },
    {
      label: "Advance %",
      type: "number",
      key: "advancePercent",
      inForm: true,
      inEdit: true,
      inTable: true,
    },
    {
      label: "Balance %",
      type: "number",
      key: "balancePercent",
      inForm: true,
      inEdit: true,
      inTable: true,
    },
    {
      label: "Milestone",
      type: "text",
      key: "milestone",
      inForm: true,
      inEdit: true,
      inTable: true,
    },
    {
      label: "Milestones",
      type: "paymentMilestones",
      key: "milestones",
      inForm: true,
      inEdit: true,
      inTable: false,
    },
    {
      label: "Default",
      type: "switch",
      key: "isDefault",
      inForm: true,
      inEdit: true,
      inTable: true,
    },
    {
      label: "Notes",
      type: "textarea",
      key: "notes",
      inForm: true,
      inEdit: true,
      inTable: false,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],

  // Category
  category: [
    {
      label: "Category Name",
      type: "text",
      key: "name",
      inForm: true,
      inTable: true,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inTable: false,
    },

    // {
    //   label: "Admin",
    //   type: "select",
    //   key: "admin",
    //   values: [],
    //   inForm: false,
    //   inTable: false,
    // },
    {
      label: "Inventory Manager",
      type: "select",
      key: "inventoryManager",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("inventoryManager"),
      inForm: true,
      inTable: false,
      required: true,
    },

    {
      label: "Created At",
      type: "text",
      key: "createdAt",
      inForm: false,
      inTable: false,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  // Sub Category
  subCategory: [
    {
      label: "Sub Category Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: false,
      required: true,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inTable: false,
      inEdit: true,
      required: true,
    },

    // {
    //   label: "Admin",
    //   type: "select",
    //   key: "admin",
    //   values: [],
    //   inForm: false,
    //   inTable: false,
    // },
    {
      label: "Category",
      type: "select",
      filterType: "multiselect",
      key: "category",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("category"),
      inForm: true,
      inTable: false,
      required: true,
    },

    {
      label: "Created At",
      type: "text",
      key: "createdAt",
      inForm: false,
      inTable: false,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  // Product
  product: [
    {
      label: "Product Name",
      type: "text",
      key: "name",
      inForm: true,
      inTable: false,
      inEdit: true,
      required: true,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inTable: false,
      inEdit: true,
      required: true,
    },

    // {
    //   label: "Admin",
    //   type: "select",
    //   key: "admin",
    //   values: [],
    //   inForm: false,
    //   inTable: false,
    // },
    {
      label: "Sub Category",
      type: "select",
      filterType: "multiselect",
      key: "subCategory",
      dependsOn: "category",
      values: [],
      dynamicValuesFn: (categoryId: string) => fetchDependentOptions("subCategory", "category", categoryId),
      inForm: true,
      inTable: true,
      inEdit: true,
      required: true,
    },
    {
      label: "Created At",
      type: "text",
      key: "createdAt",
      inForm: false,
      inTable: false,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  // Product Variant
  productVariant: [
    {
      label: "Variant Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: false,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inTable: false,
      inEdit: true,
    },
    {
      label: "Available",
      type: "boolean",
      key: "isAvailable",
      inForm: true,
      inTable: false,
      inEdit: true,
    },
    {
      label: "Created By",
      type: "text",
      key: "createdBy",
      inForm: false,
      inTable: false,
    },
    {
      label: "Live",
      type: "boolean",
      key: "isLive",
      inForm: true,
      inTable: false,
      inEdit: true,
    },
    // {
    //   label: "Admin",
    //   type: "select",
    //   key: "admin",
    //   values: [],
    //   inForm: false,
    //   inTable: false,
    // },
    {
      label: "Product",
      type: "select",
      filterType: "multiselect",
      key: "product",
      dependsOn: "subCategory",
      values: [],
      dynamicValuesFn: (subCategoryId: string) => fetchDependentOptions("product", "subCategory", subCategoryId),
      inForm: false,
      inTable: false,
      inEdit: true,
    },
    {
      label: "Created At",
      type: "text",
      key: "createdAt",
      inForm: false,
      inTable: false,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  // Product Variant Rate
  variantRate: [
    {
      label: "Price (per KG)",
      type: "number",
      key: "rate",
      inForm: true,
      inTable: true,
      inEdit: true,
    },
    {
      label: "Product Variant",
      type: "select",
      filterType: "multiselect",
      key: "productVariant",
      values: [],
      dependsOn: "product",
      dynamicValuesFn: (productId: string) => fetchDependentOptions("productVariant", "product", productId),
      inForm: false,
      inTable: true,
      // inEdit: true,
    }, {
      label: "Unit",
      type: "select",
      key: "unit",
      values: [
        { key: "KG", value: "KG" },
        { key: "MT", value: "Metric Ton (MT)" },
        { key: "Quintal", value: "Quintal" },
      ],
      inForm: true,
      inTable: true,
      inEdit: true,
      required: true,
    },
    {
      label: "Quantity (MT)",
      type: "number",
      key: "quantity",
      inForm: true,
      inTable: false,
      inEdit: true,
      required: false,
    },
    {
      label: "Inventory Status",
      type: "text",
      key: "inventoryStatus",
      inForm: false,
      inTable: false,
    },
    {
      label: "Inventory Qty",
      type: "text",
      key: "inventoryQty",
      inForm: false,
      inTable: true,
    },
    {
      label: "Commission",
      type: "number",
      key: "commission",
      inForm: true,
      inTable: true,
      inEdit: true,
    },
    {
      label: "Final Rate",
      type: "number",
      key: "finalRate",
      inForm: false,
      inTable: true,
    },

    {
      label: "Associate Name",
      type: "select",
      filterType: "multiselect",
      key: "associate",
      dynamicValuesFn: () => fetchDependentOptions("associate"),
      values: [],
      inForm: true,
      inTable: true,
      // inEdit: true,
      required: true,
    },
    {
      label: "State",
      type: "select",
      key: "state",
      filterType: "multiselect",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("state"),
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "District",
      type: "select",
      key: "district",
      filterType: "multiselect",
      dependsOn: "state",
      values: [],
      dynamicValuesFn: (stateId: string) =>
        fetchDependentOptions("district", "state", stateId),
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Division",
      type: "select",
      filterType: "multiselect",
      key: "division",
      dependsOn: "district",
      dynamicValuesFn: (districtId: string) =>
        fetchDependentOptions("division", "district", districtId),
      values: [],
      inForm: true,
      inTable: true,
    },
    {
      label: "PinCode",
      type: "select",
      filterType: "multiselect",
      key: "pincodeEntry",
      dependsOn: "division",
      dynamicValuesFn: (divisionId: string) =>
        fetchDependentOptions("pincodeEntry", "division", divisionId),
      values: [],
      inForm: true,
      inTable: true,
    },
    {
      label: "Live",
      type: "boolean",
      key: "isLive",
      inForm: true,
      inTable: false,
      inEdit: false,
    },
    {
      label: "Last Live Date",
      type: "date",
      key: "lastLiveDate",
      inForm: false,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  // Product Variant Rate
  displayedRate: [
    {
      label: "Product ",
      type: "text",
      key: "product",
      inForm: false,
      inTable: true,
    },
    {
      label: "Product Variant",
      type: "text",
      key: "productVariant",
      inForm: false,
      inTable: true,
      inEdit: true,
    },
    {
      label: "Rate (per KG)",
      type: "number",
      key: "rate",
      inForm: true,
      inTable: true,
    },
    {
      label: "Quantity (MT)",
      type: "text",
      key: "quantity",
      inForm: false,
      inTable: true,
    },
    {
      label: "Live",
      type: "boolean",
      key: "isLive",
      inForm: false,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  catalogItem: [
    {
      label: "Custom Title",
      type: "text",
      key: "customTitle",
      inForm: true,
      inTable: true,
      inEdit: true,
    },
    {
      label: "Product",
      type: "text",
      key: "product",
      inForm: false,
      inTable: true,
    },
    {
      label: "Variant",
      type: "text",
      key: "productVariant",
      inForm: false,
      inTable: true,
    },
    {
      label: "Final Price (per KG)",
      type: "number",
      key: "rate",
      inForm: false,
      inTable: true,
    },
    {
      label: "Commission",
      type: "number",
      key: "commission",
      inForm: false,
      inTable: true,
    },
    {
      label: "Quantity (MT)",
      type: "text",
      key: "quantity",
      inForm: false,
      inTable: true,
    },
    {
      label: "Live",
      type: "boolean",
      key: "isLive",
      inForm: true,
      inTable: false,
      inEdit: true,
    },
    {
      label: "Last Live Date",
      type: "date",
      key: "lastLiveDate",
      inForm: false,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],

  // Project
  projects: [
    {
      label: "Title",
      type: "text",
      key: "title",
      inForm: false,
      inTable: false,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",
      inForm: true,
      inTable: false,
      inEdit: true,
    },
    {
      label: "Custom ID",
      type: "text",
      key: "customId",
      filterType: "text",
      inForm: false,
      inTable: true,
    },
    {
      label: "Customer",
      type: "select",
      key: "customer",
      filterType: "select",
      values: [],
      inForm: true,
      inTable: true,
      inEdit: true,
      required: true,
    },
    // {
    //   label: "Admin",
    //   type: "select",
    //   key: "admin",
    //   values: [],
    //   inForm: false,
    //   inTable: false,
    // },
    {
      label: "Project Manager",
      type: "select",
      filterType: "select",
      key: "projectManager",
      values: [],
      inForm: true,
      inTable: false,
      inEdit: true,
      required: true,
    },
    {
      label: "Assignment Date ",
      type: "date",
      key: "assignmentDate",
      filterType: "date",

      inForm: true,
      inTable: true,
      inEdit: true,
    },
    {
      label: "Status",
      type: "select",
      key: "status",
      values: [],
      inForm: false,
      inTable: false,
    },
    {
      label: "Project Task",
      type: "select",
      key: "type",
      values: [],
      inForm: true,
      inTable: true,
      inEdit: true,
      required: true,
    },
    {
      label: "Location",
      type: "select",
      filterType: "multiselect",
      key: "location",
      values: [],
      inForm: true,
      inTable: true,
      inEdit: true,
      required: true,
    },
    {
      label: "Task",
      type: "textarea",
      key: "task",
      inForm: true,
      inTable: false,
      inEdit: true,
    },
    {
      label: "Order Number",
      type: "text",
      key: "orderNumber",
      inForm: true,
      inTable: false,
      inEdit: true,
    },

    {
      label: "Scheda Radio Date",
      type: "date",
      key: "schedaRadioDate",
      filterType: "date",
      inForm: true,
      inEdit: true,
      inTable: true,
    },

    {
      label: "Created At",
      type: "text",
      key: "createdAt",
      inForm: false,
      inTable: false,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  // Project
  enquiry: [
    {
      label: "Buyer Associate",
      type: "select",
      key: "buyerAssociateId",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("associate"),
      inForm: true,
      inTable: false,
      inEdit: true,
      required: true,
    },
    {
      label: "Seller Associate",
      type: "select",
      key: "sellerAssociateId",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("associate"),
      inForm: true,
      inTable: false,
      inEdit: true,
      required: true,
    },
    {
      label: "Mediator Associate (Optional)",
      type: "select",
      key: "mediatorAssociateId",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("associate"),
      inForm: true,
      inTable: false,
      inEdit: true,
      required: false,
    },
    {
      label: "Product",
      type: "select",
      key: "productId",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("product"),
      inForm: true,
      inTable: false,
      inEdit: true,
      required: true,
    },
    {
      label: "Quantity (Ton)",
      type: "number",
      key: "quantity",
      inForm: true,
      inTable: false,
      inEdit: true,
      required: true,
    },
    {
      label: "Preferred Incoterm (Optional)",
      type: "select",
      key: "preferredIncoterm",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("incoterm"),
      inForm: true,
      inTable: false,
      inEdit: true,
      required: false,
    },
    {
      label: "Supplier Commit Until (Optional)",
      type: "date",
      key: "supplierCommitUntil",
      inForm: true,
      inTable: false,
      inEdit: true,
      required: false,
    },
    {
      label: "Specifications",
      type: "textarea",
      key: "specifications",
      inForm: true,
      inTable: false,
      inEdit: true,
      required: false,
    },
    {
      label: "Customer Name",
      type: "text",
      key: "name",
      inForm: false,
      inTable: true,
      inEdit: true,
      required: true,
    },
    {
      label: "Phone Number",
      type: "number",
      key: "phoneNumber",
      filterType: "text",
      inForm: false,
      inTable: true,
    },
    {
      label: "Specifications",
      type: "textarea",
      key: "specification",
      inForm: true,
      inTable: true,
      inEdit: true,
    },
    // {
    //   label: "Customer name",
    //   type: "text",
    //   key: "name",
    //   filterType: "select",
    //   values: [],
    //   inForm: true,
    //   inTable: true,
    //   inEdit: true,
    //   required: true,
    // },

    {
      label: "Mediator Associate",
      type: "text",
      key: "mediatorAssociate",
      filterType: "select",
      inForm: false,
      inTable: true,
      inEdit: true,
      required: true,
    },
    {
      label: "Product Associate",
      type: "text",
      key: "productAssociate",
      filterType: "select",
      inForm: false,
      inTable: true,
      inEdit: true,
      required: true,
    },
    {
      label: "Associate Company",
      type: "text",
      key: "associateCompany",
      filterType: "select",
      inForm: false,
      inTable: true,
      inEdit: true,
      required: true,
    },
    {
      label: "Product",
      type: "text",
      key: "product",
      filterType: "select",
      inForm: false,
      inTable: true,
      inEdit: true,
      required: true,
    },
    {
      label: "Product Variant",
      type: "text",
      key: "productVariant",
      inForm: false,
      inTable: true,
      inEdit: true,
    },
    {
      label: "Rate",
      type: "text",
      key: "rate",
      inForm: false,
      inTable: true,
      inEdit: true,
    },
    {
      label: "Commission",
      type: "text",
      key: "commission",
      inForm: false,
      inTable: true,
      inEdit: true,
    },
    // {
    //   label: "Variant Rate| Commission",
    //   type: "text",
    //   key: "variantRate",
    //   inForm: false,
    //   inTable: true,
    //   inEdit: true,
    // },
    // {
    //   label: "Displayed Rate | Commission",
    //   type: "text",
    //   key: "displayedRate",
    //   inForm: false,
    //   inTable: true,
    //   inEdit: true,
    // },
    {
      label: "Created At",
      type: "text",
      key: "createdAt",
      inForm: false,
      inTable: false,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  enquiryProcessStatus: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inEdit: true,
      inTable: true,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],

  projectType: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inTable: true,
      required: true,
    },

    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  projectStatus: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  // Activity
  activity: [
    {
      label: "Title",
      type: "text",
      key: "title",
      filterType: "text",
      inForm: false,
      inTable: true,
      inEdit: false,
    },
    {
      label: "Description",
      type: "textarea",
      key: "description",

      inForm: true,
      inTable: false,
      inEdit: true,
    },

    {
      label: "Project",
      type: "select",
      key: "project",
      values: [],
      inForm: false,
      inTable: false,
      inEdit: false,
    },

    {
      label: "Activity Manager",
      type: "select",
      key: "activityManager",
      filterType: "multiselect",
      values: [],
      inForm: true,
      inTable: true,
      inEdit: true,
      required: true,
    },
    {
      label: "Workers",
      type: "multiselect",
      key: "worker",
      filterType: "multiselect",
      values: [],
      inForm: true,
      inTable: false,
      inEdit: true,
    },
    {
      label: "Status",
      type: "select",
      key: "status",
      values: [],
      inForm: false,
      inTable: false,
      inEdit: false,
    },
    {
      label: "Forecast Date",
      type: "week",
      key: "forecastDate",
      filterType: "date",
      inForm: true,
      inTable: true,
      inEdit: true,
    },
    {
      label: "Actual Date",
      type: "date",
      key: "actualDate",
      filterType: "date",
      inForm: false,
      inTable: false,
      inEdit: true,
    },
    {
      label: "Target Operation Date",
      type: "week",
      key: "targetOperationDate",
      filterType: "date",
      inForm: true,
      inTable: true,
      inEdit: true,
    },
    {
      label: "Target Finance  Date",
      type: "week",
      key: "targetFinanceDate",
      filterType: "date",
      inForm: false,
      inTable: false,
      inEdit: true,
    },

    {
      label: "Updated By ",
      type: "text",
      key: "updatedBy",
      inForm: false,
      inTable: true,
      inEdit: false,
    },
    {
      label: "Hours Spent",
      type: "number",
      key: "hoursSpent",
      inForm: false,
      inTable: true,
      // inEdit: true,
    },

    {
      label: "Rejection Reason",
      type: "textarea",
      key: "rejectionReason",
      inForm: false,
      inTable: false,
    },

    {
      label: "Activity Type",
      type: "select",
      key: "type",
      inForm: true,
      inTable: false,
      required: true,
    },

    {
      label: "Allow TimeSheets",
      type: "boolean",
      key: "allowTimesheets",
      inForm: true,
      inTable: false,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: false,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  activityStatus: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inTable: true,
      required: true,
    },

    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  activityType: [
    {
      label: "Name",
      type: "text",
      key: "name",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    // {
    //   label: "Active",
    //   type: "checkbox",
    //   key: "isActive",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  // TimeSheet
  timeSheet: [
    {
      label: "Activity",
      type: "select",
      key: "activity",
      values: [],
      inForm: false,
      inTable: true,
    },
    {
      label: "Note",
      type: "textarea",
      key: "note",
      inForm: true,
      inTable: true,
    },
    // {
    //   label: "Created By",
    //   type: "text",
    //   key: "createdBy",
    //   inForm: false,
    //   inTable: true,
    // },
    {
      label: "Role",
      type: "text",
      key: "createdByRole",
      inForm: false,
      inTable: true,
    },
    {
      label: "Date",
      type: "date",
      key: "date",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Start Time",
      type: "time",
      key: "startTime",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "End Time",
      type: "time",
      key: "endTime",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Created At",
      type: "dateTime",
      key: "createdAt",
      inForm: false,
      inTable: true,
    },
    {
      label: "Updated At",
      type: "dateTime",
      key: "updatedAt",
      inForm: false,
      inTable: false,
    },

    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],

  statusHistory: [
    {
      label: "Changed Role",
      type: "text",
      key: "changedRole",
      inForm: false,
      inTable: true,
      inEdit: false,
    },
    {
      label: "New Status",
      type: "text",
      key: "newStatus",
      inForm: false,
      inTable: true,
      inEdit: false,
    },
    {
      label: "Changed By",
      type: "text",
      key: "changedBy",
      inForm: false,
      inTable: true,
      inEdit: false,
    },
    {
      label: "Change Type",
      type: "text",
      key: "changeType",
      inForm: false,
      inTable: true,
      inEdit: false,
    },
    {
      label: "Changed Fields",
      type: "text",
      key: "changedFields",
      inForm: false,
      inTable: true,
      inEdit: false,
    },
    {
      label: "Changed At",
      type: "dateTime",
      key: "changedAt",
      inForm: false,
      inTable: true,
    },
  ],
  inventories: [
    {
      label: "Category",
      type: "select",
      key: "category",
      values: [],
      dynamicValuesFn: () => fetchDependentOptions("category"),
      inForm: true,
      inTable: false,
      required: true,
    },
    {
      label: "Sub Category",
      type: "select",
      key: "subCategory",
      dependsOn: "category",
      values: [],
      dynamicValuesFn: (categoryId: string) => fetchDependentOptions("subCategory", "category", categoryId),
      inForm: true,
      inTable: false,
      required: true,
    },
    {
      label: "Product",
      type: "select",
      key: "product",
      dependsOn: "subCategory",
      values: [],
      dynamicValuesFn: (subCategoryId: string) => fetchDependentOptions("product", "subCategory", subCategoryId),
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Product Variant",
      type: "select",
      key: "productVariant",
      dependsOn: "product",
      values: [],
      dynamicValuesFn: (productId: string) => fetchDependentOptions("productVariant", "product", productId),
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Quantity",
      type: "number",
      key: "quantity",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Storage Location",
      type: "select",
      key: "storageLocation",
      values: [
        { key: "NONE", value: "No Warehouse" },
        { key: "PRIVATE", value: "Private Location" },
        { key: "MY", value: "My Warehouse" },
      ],
      inForm: true,
      inTable: false,
    },
    {
      label: "Warehouse",
      type: "select",
      key: "warehouseId",
      dependsOn: "storageLocation",
      dynamicValuesFn: (storageLocation: string) => {
        const scope =
          String(storageLocation || "").toUpperCase() === "MY"
            ? "my"
            : "";
        return fetchDependentOptions("warehouse", undefined, undefined, scope ? { scope } : undefined);
      },
      inForm: true,
      inTable: false,
      showWhen: { key: "storageLocation", equals: ["MY"] },
    },
    {
      label: "Warehouse Name",
      type: "text",
      key: "warehouseName",
      inForm: false,
      inTable: true,
    },
    {
      label: "State",
      type: "select",
      key: "state",
      dynamicValuesFn: () => fetchDependentOptions("state"),
      inForm: true,
      inTable: false,
    },
    {
      label: "District",
      type: "select",
      key: "district",
      dependsOn: "state",
      dynamicValuesFn: (stateId: string) => fetchDependentOptions("district", "state", stateId),
      inForm: true,
      inTable: false,
    },
    {
      label: "Associate",
      type: "select",
      key: "associate",
      dynamicValuesFn: () => fetchDependentOptions("associate"),
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
  warehouse: [
    {
      label: "Warehouse Name",
      type: "text",
      key: "name",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Category",
      type: "select",
      key: "category",
      values: [
        { key: "GENERAL", value: "General warehouse" },
        { key: "COLD_STORAGE", value: "Cold storage" },
        { key: "BONDED", value: "Bonded warehouse" },
        { key: "AGRO", value: "Agro warehouse" },
      ],
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Address",
      type: "textarea",
      key: "address",
      inForm: true,
      inTable: false,
    },
    {
      label: "Storage Rate Per Unit",
      type: "number",
      key: "storageRatePerUnit",
      inForm: true,
      inTable: true,
      required: true,
    },
    {
      label: "Unit",
      type: "select",
      key: "unit",
      values: [
        { key: "MT", value: "MT" },
        { key: "KG", value: "KG" },
      ],
      inForm: true,
      inTable: true,
    },
    {
      label: "Listing Type",
      type: "select",
      key: "listingType",
      values: [
        { key: "PRIVATE", value: "Private" },
        { key: "RENTAL", value: "Rental" },
      ],
      inForm: true,
      inTable: true,
    },
    {
      label: "Rental Active",
      type: "boolean",
      key: "isRentalActive",
      inForm: true,
      inTable: true,
    },
    {
      label: "Active",
      type: "boolean",
      key: "isActive",
      inForm: true,
      inTable: true,
    },
    {
      label: "Actions",
      type: "action",
      key: "actions2",
      inForm: false,
      inTable: true,
    },
  ],
};

/**
 * Basic interface for an Enquiry (example)
 */
interface IEnquiry {
  _id: string;
  phoneNumber: string;
  name: string;
  variantRate: string; // or object ID
  displayRate?: string | null;
  productVariant: string;
  mediatorAssociate?: string | null;
  realAssociate: string;
  createdAt?: string;
}
